# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Blue Eye's dev-ops
email: scin21c@gmail.com
description: Digital Blue Eye(http://blog.sz21c.com)의 기술 이야기만 다루는 서브 블로그입니다.<br/>블로그 주인장이 개발자인지라 일을 하면서 알게되는 이런저런 것들, 소소한 개발 과정의 이야기를 풀어볼까 합니다.
    #> # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kr-zephyr.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  kr-zephyr

# Build settings
markdown: kramdown

disqus: dbe-dev-ops
theme: jekyll-theme-modernist

paginate: 5
simple_search: http://google.com/search